baseURL: "https://Matteo1752.github.io"
languageCode: "fr-fr"
title: "Matteo profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

pagination:
  pagerSize: 30

enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: Ap
      name: Ap et projets
      title: Ap stages
      url: /Ap
      weight: 1
    - identifier: Stages
      name: Stages
      title: Stages
      url: /stages
      weight: 2
    - identifier: Veille
      name: Veille
      title: Veille
      url: /veille
      weight: 3

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "images/Moi.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Matteo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: true
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Bonjour je suis"
    title: "COTTON Matteo."
    subtitle: "Je suis actuellement en bts sio (Service Informatiques aux Organisation) Option SISR ( Solution D'infrastructure,Systémes et Réseaux)"
    content: ". "
    image: /images/Moi.png
    bottomImage:
      enable: false
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false

      customIcons:
        - icon: /images/Moi.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "A propos de moi"
    image: "/images/Moi.png/"
    content: |-
     Je suis actuellement étudiant au Lycée Edme Bouchardon a Chaumont en BTS SIO (Services Informatiques aux Organisations).J ai choisi l'option SISR ( Solution Infrastructures,Systeme et Réseaux).
    skills:
      enable: true
      title: "Je posséde plusieurs compétences d'informatique:"
      items:
        - "Mise en place d'un serveur windows AD"
        - "Déploiement de machines par le réseau"
        - "Mise en place d'un pare-feu Stormshield"
        - "Mise en place de Proxmox"
        - "Supervision réseau avec Zabbix"
        - "Mise en place de fonctionnalités DNS,DHCP"

  # Experience
  experience:
    enable: true
    title: "Expériences professionelles"
    items:
      - job: "Stagiaire"
        company: "Forges de Bologne"
        companyUrl: "https://example.com"
        date: "20 Mars 2023 - 14 Avril 2023 et 21 Novembre 2023-8 Decembre 2023"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: "Stage réalisé en Terminal bac pro lors de mes deux période de stage"
      - job: "Stagiaire"
        company: "Conseil départemental Chaumont"
        companyUrl: "https://example.com"
        date: "17 janvier 2022 au 4 Février 2022 et 30 Mai 2022 au 8 Juillet 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: "Stage réalisé en premiere bac pro lors de mes deux periodes de stage"
      - job: "Stagiaire"
        company: "Hopital de Chaumont"
        companyUrl: "https://example.com"
        date: "27 mai 2024 au 28 juin 2024"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: "Stage réalisé lors de ma première année de BTS SIO"   
      - job: "Blanchisseur"
        company: "Hopital de Chaumont"
        companyUrl: "https://example.com"
        date: "08 juillet 2024 au 19 juillet 2024"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: "Job d'été"
      - job: "Stagiaire"
        company: "Clinique de Chaumont"
        companyUrl: "https://example.com"
        date: "6 janvier 2025 au 7 février 2025"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: "Stage réalisé lors de ma seconde année de BTS SIO"




  # Education
  education:
    enable: true
    title: "Parcours scolaire"
    index: false
    items:
      - title: "Bts SIO (Services Informatiques aux Organisations)"
        school:
          name: "Lycée Edme Bouchardon,Chaumont"
          url: "https://example.org"
        date: "2023 - 2025"
        content: |-
      - title: "Baccalauréat Pro Lycée Eugene Decomble"
        school:
          name: "Lycée Eugene Decomble,Chaumont"
          url: "https://example.org"
        date: "2021 - 2023"

        content: |-
          Au lycée Eugène Decomble j'ai pris l'option RISC (Réseaux Informatique et Systèmes Communicants)
        featuredLink:
          enable: false



  
  #Contact
  contact:
    enable: false
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
